-- 코드를 입력하세요
SELECT SUM(U.USER_ID) AS SALES_USER_ACCOUNT, SALES_USER_ACCOUNT / 
  (
    SELECT COUNT(U.USER_ID)
    FROM USER_INFO AS U, ONLINE_SALE AS O
    WHERE U.USER_ID=O.USER_ID
      AND U.JOINED LIKE '2021-%'
    GROUP BY U.USER_ID
  )
FROM USER_INFO AS U, ONLINE_SALE AS O
WHERE U.USER_ID=O.USER_ID
  AND U.JOINED LIKE '2021-%'
  AND SALES_AMOUNT > 0
GROUP BY U.USER_ID
  # AND 
  
  
