## TEST 1
# SELECT MCDP_CD AS 진료과코드, APNT_YMD  AS 5월예약건수
# FROM APPOINTMENT 
# WHERE APNT_YMD LIKE '2022-05%'
# GROUP BY MCDP_CD


## Submit code
SELECT MCDP_CD AS 진료과코드, COUNT(APNT_YMD) AS 5월예약건수
FROM APPOINTMENT 
WHERE APNT_YMD LIKE '2022-05%'
GROUP BY MCDP_CD
# ORDER BY COUNT(APNT_YMD) AND MCDP_CD
ORDER BY 2, 1
## 이부분이 포인트


## Ref
# SUBSTRUING(APNT_YMD, 1,7)
# WHERE APNT_YMD NOT BETWEEN '2017-10-01' AND '2017-10-31'
# SELECT type, COUNT(name) AS cnt FROM hero_collection GROUP BY type;